### ISSUE TITLE
No acceptor sessions found in settings

### ISSUE THREAD

**Issue by apupneja** [esanchezros/quickfixj-spring-boot-starter-examples#23]
I was trying to setup the example present at this URL(https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-and-server). I replicated all the files in my project, including the config files. However, I ran into an error

```
2023-06-18 16:43:35.763 DEBUG 1312597 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception
quickfix.ConfigError: No acceptor sessions found in settings.
	at quickfix.mina.acceptor.AbstractSocketAcceptor.createSessions(AbstractSocketAcceptor.java:259) ~[quickfixj-core-2.3.1.jar:2.3.1]
	at quickfix.mina.acceptor.AbstractSocketAcceptor.startAcceptingConnections(AbstractSocketAcceptor.java:98) ~[quickfixj-core-2.3.1.jar:2.3.1]
	at quickfix.SocketAcceptor.initialize(SocketAcceptor.java:110) ~[quickfixj-core-2.3.1.jar:2.3.1]
	at quickfix.SocketAcceptor.start(SocketAcceptor.java:103) ~[quickfixj-core-2.3.1.jar:2.3.1]
	at io.allune.quickfixj.spring.boot.starter.connection.ConnectorManager.start(ConnectorManager.java:113) ~[quickfixj-spring-boot-context-2.15.4.jar:na]
Wrapped by: io.allune.quickfixj.spring.boot.starter.exception.ConfigurationException: No acceptor sessions found in settings.
	at io.allune.quickfixj.spring.boot.starter.connection.ConnectorManager.start(ConnectorManager.java:115) ~[quickfixj-spring-boot-context-2.15.4.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-6.0.9.jar:6.0.9]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-6.0.9.jar:6.0.9]
```

Any clue on what might be causing this? 

Edit: It worked if I use https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-and-server-config-string

**Comment by esanchezros** [comment]
Hi @apupneja,

It may seem that the config file is not found in the expected locations. 

The configuration is resolved using the following approach:

By a QuickFIX/J configuration string defined by the quickfixj.server.configString property

By the presence of a quickfix.SessionSettings bean named serverSessionSettings

By a configuration file defined by the quickfixj.server.config property

By the presence of the quickfixj.server.config system property

By a quickfixj-server.cfg in the working directory or at the root of the classpath

As last resort, make sure the config entries don't have any leading spaces or tabs

**Comment by apupneja** [comment]
I actually tried to change the location for the config file, and got the error that said explicitly said that the settings file were not found. So, I assumed that wasn't the reason for the error I got before.

**Comment by esanchezros** [comment]
Could you share the project or show the application config and qfj config file?

**Comment by apupneja** [comment]
I haven't made any changes to the linked starter project. ((https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-and-server). I'm using the same config files, and the application config file.

**Comment by esanchezros** [comment]
It seems to be working correctly for me

```
java -jar simple-client-and-server-2.15.4.jar 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.12)

2023-06-19 10:10:05.863  INFO 110347 --- [           main] i.a.q.s.b.s.examples.sender.AppServer    : Starting AppServer using Java 17.0.1 on eduardo-LEX with PID 110347 (/home/eduardo/dev/projects/quickfixj-spring-boot-starter-examples/simple-client-and-server/target/simple-client-and-server-2.15.4.jar started by eduardo in /home/eduardo/dev/projects/quickfixj-spring-boot-starter-examples/simple-client-and-server/target)
2023-06-19 10:10:05.865  INFO 110347 --- [           main] i.a.q.s.b.s.examples.sender.AppServer    : No active profile set, falling back to 1 default profile: "default"
2023-06-19 10:10:06.844  INFO 110347 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8089 (http)
2023-06-19 10:10:06.856  INFO 110347 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-19 10:10:06.856  INFO 110347 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
2023-06-19 10:10:06.921  INFO 110347 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-06-19 10:10:06.921  INFO 110347 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1000 ms
2023-06-19 10:10:07.012  INFO 110347 --- [           main] i.a.q.s.b.s.c.SessionSettingsLocator     : Loading settings from 'classpath:/quickfixj-server.cfg'
2023-06-19 10:10:08.444  INFO 110347 --- [           main] i.a.q.s.b.s.c.SessionSettingsLocator     : Loading settings from 'classpath:/quickfixj-client.cfg'
2023-06-19 10:10:08.764  INFO 110347 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8089 (http) with context path ''
2023-06-19 10:10:08.766  INFO 110347 --- [           main] i.a.q.s.b.s.connection.ConnectorManager  : start: Starting ConnectorManager
2023-06-19 10:10:08.859  INFO 110347 --- [           main] quickfix.DefaultSessionSchedule          : [FIX.4.1:EXEC->BANZAI] daily, 00:00:00-UTC - 00:00:00-UTC
<20230619-08:10:08, FIX.4.1:EXEC->BANZAI, event> (Session FIX.4.1:EXEC->BANZAI schedule is daily, 00:00:00-UTC - 00:00:00-UTC)
<20230619-08:10:08, FIX.4.1:EXEC->BANZAI, event> (Created session: FIX.4.1:EXEC->BANZAI)
2023-06-19 10:10:08.867  INFO 110347 --- [           main] quickfix.SocketAcceptor                  : SessionTimer started
2023-06-19 10:10:08.888  INFO 110347 --- [           main] quickfix.mina.NetworkingOptions          : Socket option: SocketTcpNoDelay=true
2023-06-19 10:10:08.888  INFO 110347 --- [           main] quickfix.mina.NetworkingOptions          : Socket option: SocketSynchronousWrites=false
2023-06-19 10:10:08.888  INFO 110347 --- [           main] quickfix.mina.NetworkingOptions          : Socket option: SocketSynchronousWriteTimeout=30000
2023-06-19 10:10:08.903  INFO 110347 --- [           main] quickfix.SocketAcceptor                  : Listening for connections at 0.0.0.0/0.0.0.0:9877 for session(s) [FIX.4.1:EXEC->BANZAI]
2023-06-19 10:10:08.905  INFO 110347 --- [           main] i.a.q.s.b.s.connection.ConnectorManager  : start: Starting ConnectorManager
2023-06-19 10:10:08.905  INFO 110347 --- [ssage Processor] quickfix.SocketAcceptor                  : Started QFJ Message Processor
2023-06-19 10:10:08.906  INFO 110347 --- [           main] quickfix.DefaultSessionSchedule          : [FIX.4.1:BANZAI->EXEC] daily, 00:00:00-UTC - 00:00:00-UTC
<20230619-08:10:08, FIX.4.1:BANZAI->EXEC, event> (Session FIX.4.1:BANZAI->EXEC schedule is daily, 00:00:00-UTC - 00:00:00-UTC)
<20230619-08:10:08, FIX.4.1:BANZAI->EXEC, event> (Created session: FIX.4.1:BANZAI->EXEC)
2023-06-19 10:10:08.907  INFO 110347 --- [           main] quickfix.mina.NetworkingOptions          : Socket option: SocketTcpNoDelay=true
2023-06-19 10:10:08.907  INFO 110347 --- [           main] quickfix.mina.NetworkingOptions          : Socket option: SocketSynchronousWrites=false
2023-06-19 10:10:08.907  INFO 110347 --- [           main] quickfix.mina.NetworkingOptions          : Socket option: SocketSynchronousWriteTimeout=30000
<20230619-08:10:08, FIX.4.1:BANZAI->EXEC, event> (Configured socket addresses for session: [localhost/127.0.0.1:9877])
2023-06-19 10:10:08.912  INFO 110347 --- [           main] quickfix.SocketInitiator                 : SessionTimer started
2023-06-19 10:10:08.913  INFO 110347 --- [ssage Processor] quickfix.SocketInitiator                 : Started QFJ Message Processor
2023-06-19 10:10:08.922  INFO 110347 --- [ NioProcessor-2] q.mina.acceptor.AcceptorIoHandler        : MINA session created: local=/127.0.0.1:9877, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/127.0.0.1:43968
<20230619-08:10:08, FIX.4.1:BANZAI->EXEC, event> (MINA session created: local=/127.0.0.1:43968, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=localhost/127.0.0.1:9877)
2023-06-19 10:10:08.923  INFO 110347 --- [           main] i.a.q.s.b.s.examples.sender.AppServer    : Started AppServer in 3.496 seconds (JVM running for 3.929)
<20230619-08:10:09, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=6035=A34=149=BANZAI52=20230619-08:10:0956=EXEC98=0108=510=224)
<20230619-08:10:09, FIX.4.1:BANZAI->EXEC, event> (Initiated logon request)
<20230619-08:10:09, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=6035=A34=149=BANZAI52=20230619-08:10:0956=EXEC98=0108=510=224)
<20230619-08:10:09, FIX.4.1:EXEC->BANZAI, event> (Accepting session FIX.4.1:EXEC->BANZAI from /127.0.0.1:43968)
<20230619-08:10:09, FIX.4.1:EXEC->BANZAI, event> (Acceptor heartbeat set to 5 seconds)
<20230619-08:10:09, FIX.4.1:EXEC->BANZAI, event> (Received logon)
<20230619-08:10:09, FIX.4.1:EXEC->BANZAI, event> (Responding to Logon request)
<20230619-08:10:09, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=6035=A34=149=EXEC52=20230619-08:10:0956=BANZAI98=0108=510=224)
<20230619-08:10:09, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=6035=A34=149=EXEC52=20230619-08:10:0956=BANZAI98=0108=510=224)
<20230619-08:10:09, FIX.4.1:BANZAI->EXEC, event> (Received logon)
<20230619-08:10:14, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=249=BANZAI52=20230619-08:10:1456=EXEC10=232)
<20230619-08:10:14, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=249=BANZAI52=20230619-08:10:1456=EXEC10=232)
<20230619-08:10:15, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=249=EXEC52=20230619-08:10:1556=BANZAI10=233)
<20230619-08:10:15, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=249=EXEC52=20230619-08:10:1556=BANZAI10=233)
<20230619-08:10:19, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=349=BANZAI52=20230619-08:10:1956=EXEC10=238)
<20230619-08:10:19, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=349=BANZAI52=20230619-08:10:1956=EXEC10=238)
<20230619-08:10:20, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=349=EXEC52=20230619-08:10:2056=BANZAI10=230)
<20230619-08:10:20, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=349=EXEC52=20230619-08:10:2056=BANZAI10=230)
<20230619-08:10:24, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=449=BANZAI52=20230619-08:10:2456=EXEC10=235)
<20230619-08:10:24, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=449=BANZAI52=20230619-08:10:2456=EXEC10=235)
<20230619-08:10:25, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=449=EXEC52=20230619-08:10:2556=BANZAI10=236)
<20230619-08:10:25, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=449=EXEC52=20230619-08:10:2556=BANZAI10=236)
<20230619-08:10:29, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=549=BANZAI52=20230619-08:10:2956=EXEC10=241)
<20230619-08:10:29, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=549=BANZAI52=20230619-08:10:2956=EXEC10=241)
<20230619-08:10:30, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=549=EXEC52=20230619-08:10:3056=BANZAI10=233)
<20230619-08:10:30, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=549=EXEC52=20230619-08:10:3056=BANZAI10=233)
<20230619-08:10:34, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=649=BANZAI52=20230619-08:10:3456=EXEC10=238)
<20230619-08:10:34, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=649=BANZAI52=20230619-08:10:3456=EXEC10=238)
<20230619-08:10:35, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=649=EXEC52=20230619-08:10:3556=BANZAI10=239)
<20230619-08:10:35, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=649=EXEC52=20230619-08:10:3556=BANZAI10=239)
<20230619-08:10:39, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=749=BANZAI52=20230619-08:10:3956=EXEC10=244)
<20230619-08:10:39, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=749=BANZAI52=20230619-08:10:3956=EXEC10=244)
<20230619-08:10:40, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=749=EXEC52=20230619-08:10:4056=BANZAI10=236)
<20230619-08:10:40, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=749=EXEC52=20230619-08:10:4056=BANZAI10=236)
<20230619-08:10:44, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=034=849=BANZAI52=20230619-08:10:4456=EXEC10=241)
<20230619-08:10:44, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=034=849=BANZAI52=20230619-08:10:4456=EXEC10=241)
<20230619-08:10:45, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=034=849=EXEC52=20230619-08:10:4556=BANZAI10=242)
<20230619-08:10:45, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=034=849=EXEC52=20230619-08:10:4556=BANZAI10=242)
^C2023-06-19 10:10:46.712  INFO 110347 --- [ionShutdownHook] i.a.q.s.b.s.connection.ConnectorManager  : stop: Stopping ConnectorManager. Force disconnect=false
2023-06-19 10:10:46.713  INFO 110347 --- [ionShutdownHook] quickfix.SocketAcceptor                  : Logging out all sessions
<20230619-08:10:46, FIX.4.1:EXEC->BANZAI, event> (Initiated logout request)
<20230619-08:10:46, FIX.4.1:EXEC->BANZAI, outgoing> (8=FIX.4.19=4935=534=949=EXEC52=20230619-08:10:4656=BANZAI10=249)
<20230619-08:10:46, FIX.4.1:BANZAI->EXEC, incoming> (8=FIX.4.19=4935=534=949=EXEC52=20230619-08:10:4656=BANZAI10=249)
<20230619-08:10:46, FIX.4.1:BANZAI->EXEC, event> (Received logout request)
<20230619-08:10:46, FIX.4.1:BANZAI->EXEC, outgoing> (8=FIX.4.19=4935=534=949=BANZAI52=20230619-08:10:4656=EXEC10=249)
<20230619-08:10:46, FIX.4.1:BANZAI->EXEC, event> (Sent logout response)
<20230619-08:10:46, FIX.4.1:BANZAI->EXEC, event> (Disconnecting: Received logout request)
<20230619-08:10:46, FIX.4.1:EXEC->BANZAI, incoming> (8=FIX.4.19=4935=534=949=BANZAI52=20230619-08:10:4656=EXEC10=249)
<20230619-08:10:46, FIX.4.1:EXEC->BANZAI, event> (Received logout response)
<20230619-08:10:46, FIX.4.1:EXEC->BANZAI, event> (Disconnecting: Received logout response)
2023-06-19 10:10:46.914  INFO 110347 --- [ionShutdownHook] quickfix.SocketAcceptor                  : No longer accepting connections on /[0:0:0:0:0:0:0:0]:9877
2023-06-19 10:10:46.915  INFO 110347 --- [ionShutdownHook] quickfix.SocketAcceptor                  : SessionTimer canceled
2023-06-19 10:10:46.915  INFO 110347 --- [ssage Processor] quickfix.SocketAcceptor                  : Stopped QFJ Message Processor
2023-06-19 10:10:46.915  INFO 110347 --- [ionShutdownHook] i.a.q.s.b.s.connection.ConnectorManager  : stop: Stopping ConnectorManager. Force disconnect=false
2023-06-19 10:10:46.915  INFO 110347 --- [ionShutdownHook] quickfix.SocketInitiator                 : Logging out all sessions
2023-06-19 10:10:46.916  INFO 110347 --- [ionShutdownHook] quickfix.SocketInitiator                 : SessionTimer canceled
2023-06-19 10:10:46.916  INFO 110347 --- [ssage Processor] quickfix.SocketInitiator                 : Stopped QFJ Message Processor
```

**Comment by apupneja** [comment]
Oh okay then. Not sure what the issue is then. I'll use the config string as it seems to be working for me.
